name: Documentation Improvement
description: Report wrong or missing documentation
labels: [documentation]
type: task
projects: ["Deltares/124"]

body:
  - type: checkboxes
    attributes:
      label: Probabilistic library version checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have checked that this bug exists on the latest version of Probabilistic library [here](https://github.com/Deltares/ProbabilisticLibrary).
          required: true
  - type: dropdown
    id: kind
    attributes:
      description: What kind of documentation issue is this?
      label: Kind of issue
      options:
        - Documentation is wrong
        - Documentation is unclear
        - Documentation is missing
    validations:
      required: false
  - type: textarea
    id: location
    attributes:
      description: >
        If the docs are wrong or unclear please provide the URL of the documentation in question.
      label: Location of the documentation
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      description: >
        Please provide a description of the documentation problem.
      label: Documentation problem
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      description: >
        Please explain your suggested fix and why it's better than the existing documentation.
      label: Suggested fix for documentation
