---
name: Release
description: Release a new version of GeoLab Suite
labels: [release]
type: task
projects: ["Deltares/117"]
title: "release: <title>"
body:
  - type: textarea
    id: instructions-pre-release
    attributes:
      label: Checklist pre-release
      description: Execute the steps below to prepare for a release.
      value: |
        More info in our [wiki](https://github.com/Deltares/GeoLab-Suite/wiki/Release#creation-and-validation-of-a-release-candidate)
        - [ ] Release branch has been created.
        - [ ] Release pull-request has been created.
          - [ ] Pull-request has a descriptive title representing the release goals with the format `release: {release goal title}`
        - [ ] Release candidate has a related docker container.
        - [ ] Release candidate, running in the test server, is approved.
        - [ ] Release is "squash and merge" with the format `release: {release goal title}`
  - type: textarea
    id: instructions-release
    attributes:
      label: Checklist release
      value: |
        More info in our [wiki](https://github.com/Deltares/GeoLab-Suite/wiki/Release#creation-and-validation-of-a-release-candidate)
        Proceed __after__ "squash and merge" of the release pull-request.
        - [ ] GitHub has __created__ the new release tag.
        - [ ] GitHub has __published__ the new release and its related notes.
        - [ ] TeamCity has a release pin for the __release merge commit__.
        - [ ] TeamCity has __created__ the docker containers.
        - [ ] Docker containers are __deployed__ to production and test servers.
