#!/usr/bin/env python

import os
import shutil
import subprocess
import sys
from distutils.dir_util import copy_tree
from pathlib import Path

import sphinx_autosummary_accessors

# This is not needed
# sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(
    0,
    os.path.abspath("../sources/Deltares.Probabilistic.PWrapper")
)



# Ensure the current conda env's Library\bin is on PATH (Windows only)
if sys.platform.startswith("win") and "CONDA_PREFIX" in os.environ:
    conda_bin = os.path.join(os.environ["CONDA_PREFIX"], "Library", "bin")
    os.environ["PATH"] = conda_bin + os.pathsep + os.environ.get("PATH", "")

# Optional: verify pandoc is detected
try:
    subprocess.run(["pandoc", "--version"], check=True)
except Exception as e:
    print("Warning: Pandoc not found! nbsphinx will fail to render notebooks.", e)

# -- Helper functions ---------------------------------
def remove_dir_content(path: str) -> None:
    for root, dirs, files in os.walk(path):
        for f in files:
            os.unlink(os.path.join(root, f))
        for d in dirs:
            shutil.rmtree(os.path.join(root, d))
    if os.path.isdir(path):
        shutil.rmtree(path)


# NOTE: the examples/ folder in the root should be copied to docs/_examples after running sphinx
# # -- Copy notebooks to include in docs -------
if os.path.isdir("build"):
    remove_dir_content("build")
if os.path.isdir("_examples"):
    remove_dir_content("_examples")

os.makedirs("_examples")

def copy_notebooks(src_folder, dst_folder):
    if os.path.exists(dst_folder):
        shutil.rmtree(dst_folder)
    os.makedirs(dst_folder, exist_ok=True)

    for root, _, files in os.walk(src_folder):
        for f in files:
            if f.endswith(".ipynb"):
                if 'Case' in f:
                    continue
                src_file = os.path.join(root, f)
                dst_file = os.path.join(dst_folder, f)
                shutil.copy2(src_file, dst_file)

# Copy notebooks from sources into web/_examples
copy_notebooks("../sources/Deltares.Probabilistic.PWrapper.Notebooks", "_examples")

# Exclude some of the examples content:
_files_to_include = ["summary_"]


def remove_extra_files_from_dir(dir_path: Path):
    assert dir_path.exists(), "Examples dir was not correctly copied!"
    for _file in dir_path.rglob("*"):
        if _file.suffix.lower() in [".md", ".ipynb"]:
            if not any(_fi in _file.stem for _fi in _files_to_include):
                _file.unlink()


# _examples_dir = Path("_examples")
# _examples_dir.joinpath("README.md").unlink()
# remove_extra_files_from_dir(_examples_dir.joinpath("hackathons"))


if os.path.isdir("docs"):
    remove_dir_content("docs")

_src_diagrams = "../docs/_diagrams/"
_dst_diagrams = "docs/_diagrams/"
# os.makedirs(_dst_diagrams)
# for _img_file in os.listdir(_src_diagrams):
#     if not _img_file.endswith(".png"):
#         continue
#     shutil.copy((_src_diagrams + _img_file), (_dst_diagrams + _img_file))


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.

# General information about the project.
project = "Probabilistic Library"
copyright = "2026, Deltares"
author = "Rob Brinkman\\Karolina Wojciechowska\\Edwin Spee\\Matthias Hauth"


extensions = [
    "sphinx_design",
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosummary",
    "sphinx_autosummary_accessors",
    "nbsphinx",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.mermaid",
]

# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

nb_execution_mode = "off"  # notebook will not be executed during the build process
# Disable input prompts in code cells

nbsphinx_prompt_width = "0px"  # string with units
nbsphinx_show_input_prompt = False  # hides input prompts
nbsphinx_show_output_prompt = False  # hides output prompts

# -- Mermaid configuration ------------------------------
mermaid_version = "10.4.0"  # specify Mermaid version if needed
mermaid_output_format = "png"  # or "svg"
mermaid_cmd_args = ["--width", "800"]  # optional CLI args

mmdc_path = shutil.which("mmdc")
if mmdc_path is None:
    raise RuntimeError(
        "Mermaid CLI 'mmdc' not found. "
        "Install with 'npm install -g @mermaid-js/mermaid-cli' "
        "and make sure the npm global folder is on PATH."
    )

mermaid_cmd = mmdc_path  # this is necessary to render the mermaid diagrams





autosummary_generate = True  # generates stub .rst files automatically

templates_path = ["_templates", sphinx_autosummary_accessors.templates_path]



# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# # Napoleon settings
# napoleon_use_param = True
# napoleon_use_rtype = True
# napoleon_numpy_docstring = True
# napoleon_google_docstring = False
# napoleon_preprocess_types = True

suppress_warnings = ["ref.unknown_target"]

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
html_logo = "_resources/PTK_logo.png"

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    "show_nav_level": 2,
    "navbar_align": "content",
    "use_edit_page_button": True,
    "icon_links": [

        {
            "name": "Forum",
            "url": "https://github.com/Deltares/ProbabilisticLibrary/discussions",  
            "icon": "../../_resources/PTK_small_logo.png",
            "type": "local",
        },
        {
            "name": "Repo",
            "url": "https://github.com/Deltares/ProbabilisticLibrary", 
            "icon": "../../_resources/github.svg",
            "type": "local",
        },
        {
            "name": "Python",
            "url": "https://pypi.org/project/probabilistic-library",
            "icon": "../../_resources/pypi.svg",
            "type": "local",
        },
        {
            "name": "PTK",
            "url": "https://www.deltares.nl/software-en-data/producten/probabilistic-toolkit-ptk",
            "icon": "../../_resources/deltares.jpg",
            "type": "local",
        },


    ],
    "logo": {
        "text": "Probabilistic Library",
    },
    "navbar_end": ["navbar-icon-links"],  # remove dark mode switch
}

html_context = {
    "github_url": "https://github.com",  # or your GitHub Enterprise interprise
    "github_user": "Deltares",
    "github_repo": "ProbabilisticLibrary",
    "github_version": "master",  # FIXME
    "doc_path": "docs",
    "default_mode": "light",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_resources"]
html_css_files = ["theme-deltares.css", "python-code-block-style.css", "custom.css"]


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "ProbLibdoc"


# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}


# Allow errors in notebooks
nbsphinx_allow_errors = True
# Do not execute the scripts during the build process.
nbsphinx_execute = "never"

autodoc_typehints = (
    "description"  # put type hints in the description instead of signature
)
add_module_names = False  # shorten class names in the docs
